In [2]:
import numpy as np

In [ ]:
# Create an array of 10 zeros 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 10 ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 10 fives

In [8]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Create an array of all the even integers from 10 to 50

In [10]:
arr1=np.arange(10,51)

In [11]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [22]:
arr1=np.arange(10,51,2)

In [23]:
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
mat1=np.arange(0,9)

In [26]:
mat1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
mat1=mat1.reshape(3,3)

In [29]:
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3x3 identity matrix

In [37]:
mat_i=np.identity(3,dtype=int)

In [38]:
mat_i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# Use NumPy to generate a random number between 0 and 1

In [48]:
r1=np.random.rand()

In [49]:
r1

0.6010477377947944

In [ ]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [52]:
np.random.randn()

0.44326720168761236

In [53]:
np.random.randn(1)

array([-0.14053032])

In [57]:
np.random.rand(25)

array([0.16354048, 0.08591912, 0.23090602, 0.29734349, 0.00680308,
       0.06246485, 0.93400243, 0.23539222, 0.8337232 , 0.43379215,
       0.84578584, 0.18709886, 0.49487177, 0.14707307, 0.64480469,
       0.63114213, 0.38139787, 0.23022005, 0.36501592, 0.20931142,
       0.71276304, 0.85210888, 0.44823398, 0.99163808, 0.6870278 ])

In [58]:
np.random.rand(25).shape

(25,)

In [59]:
np.random.rand(25).reshape(5,5)

array([[0.24868572, 0.49976835, 0.24778566, 0.16414572, 0.38628975],
       [0.40788004, 0.18276276, 0.74194056, 0.66241301, 0.16252512],
       [0.2420593 , 0.44572829, 0.82958713, 0.66920223, 0.69778641],
       [0.12930348, 0.1153584 , 0.28506207, 0.63496921, 0.01183061],
       [0.5175797 , 0.31999615, 0.9920247 , 0.6431989 , 0.54617023]])

In [6]:
arr2=np.arange(1,101)

In [7]:
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
arr2=arr2.reshape(10,10)

In [10]:
arr2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [11]:
arr2/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#   Numpy Indexing and Selection
#   Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
arr=np.arange(1,26).reshape(5,5)

In [14]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [18]:
arr[3,4]

20

In [19]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
arr[4,0:]

array([21, 22, 23, 24, 25])

In [22]:
arr[3: ,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
#Get the sum of all the values in mat
arr.sum()

325

#Get the standard deviation of the values in mat

In [24]:
arr.std()

7.211102550927978

In [25]:
#Get the sum of all the columns in mat


arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
#NumPy Operations
#Arithmetic
You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [27]:
arr=np.arange(0,10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
arr/arr

<ipython-input-32-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
1/arr

<ipython-input-33-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [34]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# Universal Array Functions
Numpy comes with many universal array functions, 
which are essentially just mathematical operations you can use to perform the operation across the array

In [35]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [36]:
#exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [37]:
np.max(arr)

9

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [39]:
np.log(arr)

<ipython-input-39-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])